export const Privileges = {
  // Admin
  ADMIN_BASIC: 0,
  ADMIN_UPDATE: 1,
  ADMIN_DELETE: 2,
  // Users global
  USERS_ACCESSIBLE: 20,
  ADD_USERS: 21,
  DELETE_USERS: 22,
  UPDATE_USERS: 23,
  UPDATE_USER_PRIVILEGES: 24,
  // Users group
  GROUP_USERS_ACCESSIBLE: 30,
  GROUP_DELETE_USERS: 31,
  GROUP_UPDATE_USERS: 32,
  GROUP_UPDATE_USER_PRIVILEGES: 33,
  // Groups
  GROUPS_ACCESSIBLE: 40,
  CREATE_GROUPS: 41,
  DELETE_GROUPS: 42,
  UPDATE_GROUPS: 43,
  UPDATE_GROUP_PRIVILEGES: 44,
  ADD_USERS_TO_GROUPS: 45,
  DELETE_USERS_FROM_GROUPS: 46,
  // Contracts
  SEE_ALL_CONTRACTS: 50,
  CREATE_CONTRACTS: 51,
  UPDATE_CONTRACTS: 52,
  SEE_GROUP_CONTRACTS: 55,
  CREATE_GROUP_CONTRACTS: 56,
  UPDATE_GROUP_CONTRACTS: 57,
  // Clients
  SEE_ALL_CLIENTS: 60,
  CREATE_CLIENTS: 61,
  DELETE_CLIENTS: 62,
  UPDATE_CLIENTS: 63,
} as const;

export const PrivilegeLabels: Record<number, string> = {
  0: "Admin Basic",
  1: "Admin Update",
  2: "Admin Delete",
  20: "Users Accessible",
  21: "Add Users",
  22: "Delete Users",
  23: "Update Users",
  24: "Update User Privileges",
  30: "Group Users Accessible",
  31: "Group Delete Users",
  32: "Group Update Users",
  33: "Group Update User Privileges",
  40: "Groups Accessible",
  41: "Create Groups",
  42: "Delete Groups",
  43: "Update Groups",
  44: "Update Group Privileges",
  45: "Add Users to Groups",
  46: "Delete Users from Groups",
  50: "See All Contracts",
  51: "Create Contracts",
  52: "Update Contracts",
  55: "See Group Contracts",
  56: "Create Group Contracts",
  57: "Update Group Contracts",
  60: "See All Clients",
  61: "Create Clients",
  62: "Delete Clients",
  63: "Update Clients",
};
