import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.scss";
import { LanguageContextProvider } from "@/context/LanguageContex";
import { AuthContextProvider } from "@/context/AuthContext";
import { UserContextProvider } from "@/context/UserContext";
import { createTheme, ThemeProvider } from "@mui/material/styles";

const theme = createTheme({
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ThemeProvider theme={theme}>
          <LanguageContextProvider>
            <AuthContextProvider>
              <UserContextProvider>
                {children}
              </UserContextProvider>
            </AuthContextProvider>
          </LanguageContextProvider>
        </ThemeProvider>;
      </body>
    </html>
  );
}
